Repository tl-its-umich-edu/remote-office-hours-queue, pull requests merged in 2020-10, with the labels that each got.

#170 Add missing QuerySet import
  src/officehours_api/serializers.py
Labels: back end, bug

#171 Notifications
  README.md
  service/base/kustomization.yaml
  src/assets/src/components/edit.tsx
  src/assets/src/components/preferences.tsx
  src/assets/src/containers/app.tsx
  src/assets/src/models.ts
  src/assets/src/services/api.ts
  src/assets/src/validation.ts
  src/officehours/makemigrations_settings.py
  src/officehours/settings.py
  src/officehours_api/consumers.py
  src/officehours_api/migrations/0019_auto_20201013_1539.py
  src/officehours_api/migrations/0020_auto_20201013_1550.py
  src/officehours_api/models.py
  src/officehours_api/notifications.py
  src/officehours_api/serializers.py
  src/officehours_api/tests.py
  src/officehours_api/views.py
  src/officehours_ui/templates/base.html
  src/officehours_ui/urls.py
  src/package-lock.json
  src/package.json
  src/requirements.txt
Labels: back end, dependencies, enhancement, front end

#177 Fix missing uvloop dependency on build
  src/Dockerfile
Labels: bug

#187 Lock pip dependencies in Dockerfile (#186)
  src/Dockerfile
Labels: dependencies, housekeeping
