Repository tl-its-umich-edu/remote-office-hours-queue, pull requests merged in 2020-11, with the labels that each got.

#195 Prompt user to refresh after failed WebSocket reconnects (#168)
  src/assets/src/hooks/useWebSocket.ts
Labels: bug, front end

#199 Move aria-label to Form.Control components (#159)
  src/assets/src/components/common.tsx
Labels: accessibility, bug, front end

#203 Keep focus on button when Copy button is clicked (#202)
  src/assets/src/components/common.tsx
Labels: accessibility, bug, front end

#200 Use blue focus indicator for .btn-warning (#158)
  src/officehours_ui/static/css/main.css
Labels: accessibility, front end

#209 Add space between sentences for Manage Hosts instructions
  src/assets/src/components/queueEditors.tsx
Labels: bug, front end

#216 Add "Back to Queue" button to Queue Settings page (#208)
  src/assets/src/components/queueSettings.tsx
Labels: enhancement, front end

#218 Add Profile fields to User page on admin site (#215)
  src/officehours_api/admin.py
Labels: back end, enhancement

#217 Add Manage link to Add Queue breadcrumbs (#95)
  src/assets/src/components/addQueue.tsx
Labels: bug, front end

#211 Adjust text of SMS notifications (#210)
  src/officehours_api/notifications.py
Labels: back end, enhancement

#222 Fix check for changed values in Queue Settings to enable blank description (#221)
  src/assets/src/components/queueSettings.tsx
Labels: bug, front end

#223 Fix admin by removing "reverse" from module scope (#224)
  src/officehours_api/notifications.py
Labels: back end, bug

#237 Reorganize Meeting Actions cell of meetings table
  src/assets/src/components/queueManager.tsx
Labels: enhancement, front end
