Repository tl-its-umich-edu/remote-office-hours-queue, pull requests merged in 2020-12, with the labels that each got.

#257 Add userWebSocketError to errorSources (#256)
  src/assets/src/components/queueManager.tsx
Labels: bug, front end

#260 Give Badge and Join Info even spacing in MeetingDetails cell on QueueManagerPage
  src/assets/src/components/meetingTables.tsx
Labels: bug, front end

#273 Fix usage of Meeting.line_place, text of alerts on attendee queue page (#260)
  src/assets/src/components/queue.tsx
Labels: bug, front end

#279 Provide hosts a different meeting URL (#265, #266)
  src/assets/src/components/meetingTables.tsx
  src/assets/src/models.ts
  src/officehours_api/backends/bluejeans.py
  src/officehours_api/backends/zoom.py
Labels: back end, enhancement, front end

#284 Change VC docs link text, fix default zoom docs link (#280)
  src/assets/src/components/queue.tsx
  src/officehours/settings.py
Labels: back end, bug, front end

#285 Update get_line_length serializer method to count only un-started meetings (#270)
  src/officehours_api/serializers.py
Labels: back end, bug

#288 Update README for 1.4 release (#286)
  README.md
Labels: documentation

#291 Build Zoom start_url to exclude ZAK
  src/officehours/settings.py
  src/officehours_api/backends/zoom.py
Labels: back end

#290 Use friendly name of backend in auth_prompt
  src/officehours_ui/templates/officehours_ui/auth_prompt.html
  src/officehours_ui/views.py
Labels: front end

#292 Fix error when assignee changes backend_type
  src/officehours_api/serializers.py
Labels: bug

#293 Use backend friendly_name in "disallow" error message
  src/assets/src/components/addQueue.tsx
  src/assets/src/components/queueSettings.tsx
  src/assets/src/hooks/useValidation.ts
  src/assets/src/validation.ts
Labels: front end

#297 "You're up next" alert should always be warning variant (#295)
  src/assets/src/components/queue.tsx
Labels: front end

#299 Add ZOOM_SIGN_IN_HELP to secrets
  service/base/kustomization.yaml
Labels: config change
