Repository tl-its-umich-edu/remote-office-hours-queue, pull requests merged in 2020-09, with the labels that each got.

#149 Remove self-focusing code from AddAttendeeForm (#138)
  src/assets/src/components/edit.tsx
Labels: bug, front end

#150 Right-align navigation bar dropdown (#119)
  src/officehours_ui/templates/base.html
Labels: bug, front end

#146 1.2 Fixes
  service/base/kustomization.yaml
  service/base/web-autoscaler.yaml
  service/overlays/dev/kustomization.yaml
  service/overlays/prod/kustomization.yaml
  service/overlays/prod/web-autoscaler.yaml
  service/overlays/qa/kustomization.yaml
  service/overlays/qa/web-autoscaler.yaml
  src/assets/src/components/common.tsx
  src/assets/src/components/edit.tsx
  src/assets/src/components/home.tsx
  src/assets/src/components/manage.tsx
  src/assets/src/components/search.tsx
  src/assets/src/hooks/useAutoRefresh.ts
  src/assets/src/hooks/useWebSocket.ts
  src/assets/src/models.ts
  src/assets/src/services/api.ts
  src/assets/src/services/sockets.ts
  src/assets/src/utils.ts
  src/officehours/asgi.py
  src/officehours/settings.py
  src/officehours_api/consumers.py
  src/officehours_api/permissions.py
  src/officehours_api/routing.py
  src/officehours_api/serializers.py
  src/officehours_api/urls.py
  src/officehours_api/views.py
  src/officehours_ui/static/css/main.css
  src/officehours_ui/templates/base.html
  src/package-lock.json
  src/package.json
Labels: bug, enhancement

#143 Refactor EditToggleField and stateless form components, consolidate client-side validation (#108)
  src/assets/src/components/common.tsx
  src/assets/src/components/edit.tsx
  src/assets/src/components/manage.tsx
  src/assets/src/components/queue.tsx
  src/assets/src/utils.ts
  src/assets/src/validation.ts
  src/officehours_ui/static/css/main.css
  src/package-lock.json
  src/package.json
Labels: enhancement, front end
