Repository tl-its-umich-edu/remote-office-hours-queue, pull requests merged in 2023-06, with the labels that each got.

#415 Remove `console.warn` from `validateString` (#413)
  src/assets/src/validation.ts
Labels: bug, front end

#419 Create `Dockerfile.openshift`, modify service artifacts to use namespaced images (#418)
  service/base/build.yaml
  service/base/redis-deployment.yaml
  src/Dockerfile.openshift
Labels: enhancement, dependencies

#375 Update css to change menu icon for small screens
  src/officehours_ui/static/css/main.css
  src/officehours_ui/templates/base.html
Labels: enhancement, front end

#402 fixed issues 369 and 298
  src/officehours_ui/static/css/main.css
  src/officehours_ui/static/favicon.ico
  src/officehours_ui/static/robots.txt
  src/officehours_ui/tests.py
  src/officehours_ui/urls.py
Labels: enhancement, back end

#421 Fixes #420 - Remove args and command from service so it will use the Dockerfile values
  service/base/web-deployment.yaml
  service/overlays/prod/deployment.yaml
  service/overlays/qa/deployment.yaml
Labels: bug, dependencies

#423 Remove alert and unused utility function (#236)
  src/assets/src/components/search.tsx
  src/assets/src/utils.ts
Labels: front end

#428 Switch to `python:3.10-slim-bullseye` (#427)
  src/Dockerfile
  src/Dockerfile.openshift
Labels: bug, dependencies, deployment

#433 Return response in overridden update method (#432)
  src/officehours_api/test_views.py
  src/officehours_api/views.py
Labels: bug, back end

#439 Modify per UX suggestions (#438)
  src/assets/src/components/addQueue.tsx
  src/assets/src/components/queueEditors.tsx
Labels: enhancement, front end
